#Settings
theme: jekyll-theme-cayman
title: Dhruval's Technical Portfolio
description: Hello! Welcome to my portfolio - My name is Dhruv and I'm an Electrical Engineering graduate from The University of British Columbia (UBC), with over 4 years of work experience in the Defense and Renewable Energy industries as a Systems Engineer. Using this portfolio, I'd like to take you through some of the most interesting projects I have worked on over the years. Enjoy!
url: 'http://www.dhruvalshahportfolio.com'



