#Settings
theme: jekyll-theme-cayman
title: Dhruval's Technical Portfolio
description: Hello! Welcome to my portfolio - my name is Dhruv and I'm an Electrical Engineering graduate from The University of British Columbia (UBC), with over 4 years of work experience in the Defense and Renewable Energy industries. Using this portfolio, I'd like to take you through some of the projects I have worked on over the years.
url: 'http://www.dhruvalshahportfolio.com'



