#Settings
theme: jekyll-theme-cayman
title: Dhruval's Technical Portfolio
description: Hello! I'm an Electrical Engineering graduate from The University of British Columbia (UBC), with over 4 years of work experience in the Defense and Renewable Energy industries.
url: 'http://www.dhruvalshahportfolio.com'



